spring:
  application:
    name: greeting-service
    
greeting-service:
  greeting: "Hello"
  default-value: "Mundo"
  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
